# Generated by Django 5.1.2 on 2024-11-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='categories',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='nota',
            new_name='note',
        ),
    ]
